# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - fairino5_v6_group_controller
    - hand_controller

  fairino5_v6_group_controller:
    type: FollowJointTrajectory
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    action_ns: follow_joint_trajectory
  hand_controller:
    type: FollowJointTrajectory
    joints:
      - gripper_joint1_left
    action_ns: follow_joint_trajectory